version: '3.8'

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: node app.js
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  media-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: node server.js
    ports:
      - "1935:1935"
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
